// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00


#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

extern void eventSoins(lv_event_t * e);
extern void eventPhototypes(lv_event_t * e);
extern void PlayButtonevent(lv_event_t * e);
extern void PauseButtonevent(lv_event_t * e);
extern void StopButtonevent(lv_event_t * e);
extern void ui_event_ExitButton(lv_event_t * e);
extern void event_lang_dropdown(lv_event_t * e);

extern void afficher_infos_soin();
extern void start_soin_timer();
extern void soin_timer_callback(lv_timer_t *timer);
extern void control_leds();
extern int tps1;
extern int tps2;
extern lv_timer_t *soin_timer;

extern uint32_t temps_phase1_restants;
extern uint32_t temps_phase2_restants;
extern int temps_total_restants;
extern lv_obj_t *bar_progression;
extern bool soin_en_pause;
extern bool ble_connecte ;

extern bool soin_en_cours ;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
