// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#include "ui.h"
#include <string.h>
#include <stdio.h>
#include "lang.h"

// Initialisation globale

Phototype *phototype_selectionne = NULL; 
Soin *soin_selectionne = NULL;
lv_timer_t *soin_timer = NULL;

lv_obj_t *bar_progression;
bool soin_en_pause = false;
bool soin_en_cours = false;

void afficher_infos_soin();
void start_soin_timer();
void soin_timer_callback(lv_timer_t *timer);
void control_leds();

int temps_total_restants = 0;

Phase *phase_precedente = NULL;
int tps1 = 0;
int tps2 = 0;

void eventPhototypes(lv_event_t *e)
{
    control_leds();

    lv_obj_t *Phototypes = lv_event_get_target(e);
    int index = lv_dropdown_get_selected(Phototypes);  // Récupère l'index sélectionné

    if (index >= 0 && index < NB_Photo) {  // Vérifie que l'index est valide
        phototype_selectionne = &phototypes[index];  // Récupère le phototype sélectionné

        // Met à jour les labels avec le nom du phototype sélectionné
        lv_label_set_text(ui_NomPhototype, phototype_selectionne->nom);

        // Active la liste déroulante des soins
        lv_obj_clear_state(ui_SoinsLists, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_SoinsLists, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Fond blanc quand actif

    } else {
        // Si aucun phototype valide n’est sélectionné
        phototype_selectionne = NULL;

        // Désactive la liste des soins
        lv_obj_add_state(ui_SoinsLists, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_SoinsLists, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);
    }

    // Met à jour l'état du bouton Play selon l'état actuel
    update_play_button_state();
}


void eventSoins(lv_event_t *e)
{
    control_leds();
    if (soin_en_cours) return;

    // Si aucun phototype sélectionné, quitter la fonction
    if (phototype_selectionne == NULL) return;  // Sortie si phototype non sélectionné

    lv_obj_t *Soins = lv_event_get_target(e);
    int index = lv_dropdown_get_selected(Soins);  // Récupère l'index du soin sélectionné

    if (index >= 0 && index < NB_SOIN) {
        soin_selectionne = &soins[index];

        // Affiche le nom du soin
        char soin_nom_traduit[64];
        lv_dropdown_get_selected_str(Soins, soin_nom_traduit, sizeof(soin_nom_traduit));
        //char buffer[128];
        //snprintf(buffer, sizeof(buffer), "%s - %s", soin_nom_traduit, phototype_selectionne->nom);
        lv_label_set_text(ui_NomsoinLabel, soin_nom_traduit);

        // Calcule les temps ajustés avec le coefficient du phototype
        float coef_soin = phototype_selectionne->coef_soins;
        tps1 = round(soin_selectionne->phase1.duree * coef_soin);
        tps2= round(soin_selectionne->phase2.duree * coef_soin);
        int total = tps1 + tps2;
        // Met à jour les labels avec le temps total ajusté
        lv_label_set_text_fmt(ui_TempstotalsoinsLabel, "%d min %02d s", total / 60, total % 60);
        
    } else {
        soin_selectionne = NULL;
    }

    // Met à jour l'état du bouton Play selon l'état actuel
    update_play_button_state(); 
}


void PlayButtonevent(lv_event_t *e)
{
    if (phototype_selectionne == NULL || soin_selectionne == NULL) return;

    if (!soin_timer) {
        // Nouveau soin à démarrer
        afficher_infos_soin();
        start_soin_timer();
    } else if (soin_en_pause) {
        // Reprise du soin en pause
        soin_en_pause = false;
        lv_timer_resume(soin_timer);
        soin_en_cours = true;

        // Remet le bouton pause à son état d’origine
        lv_obj_set_style_bg_color(ui_PauseButton, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT); // Jaune
    }

    // Mise à jour des LEDs selon l’état (démarrage ou reprise)
    control_leds();

    // Verrouillage des listes et autres contrôles pendant soin
    lv_obj_add_state(ui_SoinsLists, LV_STATE_DISABLED);
    lv_obj_add_state(ui_PhototypeLists, LV_STATE_DISABLED);
    lv_obj_add_state(ui_LangDropdown, LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_LangDropdown, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_PhototypeLists, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);

    // Mise à jour des états des boutons
    play_button_active = true;
    pause_button_active = true;

    update_play_button_state();
    update_pause_button_state();
    update_stop_button_state();

    // Désactivation du bouton Play (empêche double-clic)
    lv_obj_add_state(ui_PlayButton, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
}



void PauseButtonevent(lv_event_t *e)
{	
	soin_en_cours = false;
	control_leds();
    if (phototype_selectionne != NULL && soin_selectionne != NULL && play_button_active) {

        // Active pause
        soin_en_pause = true;
        pause_button_active = true;
        play_button_active = false;
		
		lv_obj_add_state(ui_SoinsLists, LV_STATE_DISABLED);
		lv_obj_add_state(ui_PhototypeLists, LV_STATE_DISABLED);
        lv_obj_add_state(ui_LangDropdown, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_LangDropdown, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);
		lv_obj_set_style_bg_color(ui_PhototypeLists, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);

        if (soin_timer != NULL) {
            lv_timer_pause(soin_timer);

            // Change couleur et texte
            lv_obj_set_style_bg_color(ui_PauseButton, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Orange
            //lv_label_set_text(ui_Label3, "Replay");
        }

        update_play_button_state();
        update_pause_button_state();
        update_stop_button_state();
    }
}


void StopButtonevent(lv_event_t *e)
{
    if (soin_timer) {
        lv_timer_del(soin_timer);  // Remets-le pour bien libérer le timer
        soin_timer = NULL;
    }

    soin_en_pause = false;
	soin_en_cours = false;
    play_button_active = false;
    pause_button_active = false;
	control_leds();
	

    // Réinitialise les sélections
    phototype_selectionne = NULL;
    soin_selectionne = NULL;
	temps_total_restants = 0;

    // Réinitialise l'affichage
    lv_dropdown_set_selected(ui_PhototypeLists, 0);
    lv_dropdown_set_selected(ui_SoinsLists, 0);

    // active phototype
    lv_obj_clear_state(ui_LangDropdown, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_LangDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Fond blanc quand actif
	lv_obj_clear_state(ui_PhototypeLists, LV_STATE_DISABLED);
	lv_obj_set_style_bg_color(ui_PhototypeLists, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Fond blanc quand actif
    // Désactive soins
	lv_obj_add_state(ui_SoinsLists, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_SoinsLists, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);

    lv_label_set_text_fmt(ui_TempsrestantsoinsLabel, "%d min %02d s", 00, 00); 

    update_play_button_state();
    update_pause_button_state();
    update_stop_button_state();

    // Supprime la barre de progression
    if (bar_progression != NULL) {
        lv_obj_del(bar_progression);
        bar_progression = NULL;
    }
}

