// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#include "../ui.h"

void ui_BLEScreen_screen_init(void)
{
    ui_BLEScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BLEScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BLEScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BLEScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ExitButton = lv_imgbtn_create(ui_BLEScreen);
    lv_imgbtn_set_src(ui_ExitButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1985134446, NULL);
    lv_obj_set_width(ui_ExitButton, 146);
    lv_obj_set_height(ui_ExitButton, 152);
    lv_obj_set_x(ui_ExitButton, 3);
    lv_obj_set_y(ui_ExitButton, 139);
    lv_obj_set_align(ui_ExitButton, LV_ALIGN_CENTER);

    ui_Image1 = lv_img_create(ui_BLEScreen);
    lv_img_set_src(ui_Image1, &ui_img_ble_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 565
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 183
    lv_obj_set_x(ui_Image1, -6);
    lv_obj_set_y(ui_Image1, -23);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image1, lv_color_hex(0xF2BAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_BLEScreen);
    lv_img_set_src(ui_Image3, &ui_img_mostleds_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -8);
    lv_obj_set_y(ui_Image3, -171);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ExitButton, ui_event_ExitButton, LV_EVENT_ALL, NULL);

}
