// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#include "../ui.h"

void ui_MenuSoins_screen_init(void)
{
    ui_MenuSoins = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuSoins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuSoins, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSoins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhototypeLists = lv_dropdown_create(ui_MenuSoins);
    lv_dropdown_set_options(ui_PhototypeLists, "Type 1-2\nType 3-4\nType 5-6");
    lv_obj_set_width(ui_PhototypeLists, 243);
    lv_obj_set_height(ui_PhototypeLists, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PhototypeLists, -201);
    lv_obj_set_y(ui_PhototypeLists, -200);
    lv_obj_set_align(ui_PhototypeLists, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PhototypeLists, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_PhototypeLists, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PhototypeLists, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PhototypeLists, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_PhototypeLists), lv_color_hex(0x060606),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_PhototypeLists), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_PhototypeLists), &ui_font_Roboto_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoinsLists = lv_dropdown_create(ui_MenuSoins);
    lv_dropdown_set_options(ui_SoinsLists,
                            "Acnée\nBouton lèvre\nViellissement Cutané\nMasque\nRougeur\nCoup de Soleil\nOuverture de Peau");
    lv_dropdown_set_text(ui_SoinsLists, "Soins");
    lv_obj_set_width(ui_SoinsLists, 161);
    lv_obj_set_height(ui_SoinsLists, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoinsLists, 169);
    lv_obj_set_y(ui_SoinsLists, -198);
    lv_obj_set_align(ui_SoinsLists, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SoinsLists, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_SoinsLists, lv_color_hex(0x0B0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoinsLists, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoinsLists, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_SoinsLists), lv_color_hex(0x030303),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_SoinsLists), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SoinsLists), &ui_font_Roboto_24,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_MenuSoins);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 549);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 18);
    lv_obj_set_y(ui_Slider1, -5);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Button1 = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 88);
    lv_obj_set_x(ui_Button1, -232);
    lv_obj_set_y(ui_Button1, 141);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xE61414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 90);
    lv_obj_set_x(ui_Button2, -3);
    lv_obj_set_y(ui_Button2, 145);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 83);
    lv_obj_set_x(ui_Button3, 215);
    lv_obj_set_y(ui_Button3, 144);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xB7F80E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_Label3, 617);
    lv_obj_set_height(ui_Label3, 87);
    lv_obj_set_x(ui_Label3, 19);
    lv_obj_set_y(ui_Label3, -87);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Peau à tendance acnéique et probléme d'ouverture de peau récent (&éà@è'\")");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x050404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
