// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#include "../ui.h"
#include "../ui_events.h"
#include <string.h>
#include "../lang.h"

//phototypes variables et attributs
Phototype phototypes[] = {
    { .nom = "PI - PII", .coef_soins = 1.0f },
    { .nom = "PIII - PIV", .coef_soins = 1.25f },
    { .nom = "PV - PVI", .coef_soins = 1.5f }
};

//soins variable et attributs
/*Soin soins[NB_SOIN] = {
    {TEXT_SOIN_ACNE, 3 * 60, 9 * 60},
    {TEXT_SOIN_PEAU_OUVERTE, 6 * 60, 0},
    {TEXT_SOIN_SOLEIL, 6 * 60, 0},
    {TEXT_SOIN_BOUTON, 4 * 60, 4 * 60},
    {TEXT_SOIN_MASQUE, 6 * 60, 0},
    {TEXT_SOIN_ROUGEUR, 6 * 60, 0},
    {TEXT_SOIN_VIEILLISSEMENT, 6 * 60, 0}
};*/
// Déclaration des commandes (avec taille fixe)
const uint8_t commandeRouge[] = { 'R', 'E', 'D' };
const uint8_t commandeBleu[]  = { 'B', 'L', 'U', 'E' };
const uint8_t commandeJaune[] = { 'Y', 'E', 'L', 'L', 'O', 'W' };
const uint8_t commandeVert[]  = { 'G', 'R', 'E', 'E', 'N' };
const uint8_t commandeStop[]  = { 'S', 'T', 'O', 'P' };

/* couleurRouge  = lv_color_hex(0xFF0000);
 couleurBleu   = lv_color_hex(0x0000FF);
 couleurVert   = lv_color_hex(0x00FF00);
lv_color_t couleurJaune  = lv_color_hex(0xFFFF00);
lv_color_t couleurOrange = lv_color_hex(0xFFA500);
lv_color_t couleurRose   = lv_color_hex(0xFFC0CB);
lv_color_t couleurBlanc  = lv_color_hex(0xFFFFFF);
lv_color_t couleurGris   = lv_color_hex(0xAAAAAA);*/

Soin soins[NB_SOIN] = {
    {
        TEXT_SOIN_ACNE,
        {3 * 60, "rouge", commandeRouge, sizeof(commandeRouge), 0xFF0000},
        {9 * 60, "vert",  commandeVert, sizeof(commandeVert),  0x00FF00}
    },
    {
        TEXT_SOIN_PEAU_OUVERTE,
        {6 * 60, "bleu", commandeBleu, sizeof(commandeBleu), 0x0000FF},
        {1 * 60, "rouge", commandeRouge, sizeof(commandeRouge), 0xFF0000}
    },
    {
        TEXT_SOIN_SOLEIL,
        {6 * 60, "jaune", commandeJaune, sizeof(commandeJaune), 0xFFFF00},
        {1 * 60, "vert", commandeVert, sizeof(commandeVert), 0x00FF00}
    },
    {
        TEXT_SOIN_BOUTON,
        {4 * 60, "vert", commandeVert, sizeof(commandeVert), 0x00FF00},
        {4 * 60, "rouge", commandeRouge,sizeof(commandeRouge), 0xFF0000}
    },
    {
        TEXT_SOIN_MASQUE,
        {6 * 60, "rouge", commandeRouge, sizeof(commandeRouge), 0xFF0000},
        {1 * 60, "jaune", commandeJaune, sizeof(commandeJaune), 0xFFFF00}
    },
    {
        TEXT_SOIN_ROUGEUR,
        {6 * 60, "rouge", commandeRouge, sizeof(commandeRouge), 0xFF0000},
        {1 * 60, "vert", commandeVert, sizeof(commandeVert), 0x00FF00}
    },
    {
        TEXT_SOIN_VIEILLISSEMENT,
        {6 * 60, "bleu", commandeBleu, sizeof(commandeBleu), 0x0000FF},
        {1 * 60, "rouge", commandeRouge, sizeof(commandeRouge), 0xFF0000}
    },
};


void ui_MenuSoins_screen_init(void)
{
    ui_MenuSoins = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuSoins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuSoins, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSoins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MenuSoins, lv_color_hex(0xA8AAB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MenuSoins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MenuSoins, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

   
       // Langues Dropdown
// Fonction qui met à jour les options du dropdown langues
void update_dropdown_languages(void) {
    const char* options =
        "English\n"
        "French\n"
        "Spanish\n"
        "German\n"
        "Italian\n"
        "Portuguese\n"
        "Dutch";
    lv_dropdown_set_options(ui_LangDropdown, options);
}

// Positionne la sélection du dropdown selon la langue courante
void set_dropdown_language_selection(void) {
    for (int i = 0; i < LANG_DROPDOWN_COUNT; i++) {
        if (language_ids[i] == current_language) {
            lv_dropdown_set_selected(ui_LangDropdown, i);
            return;
        }
    }
    // Sélection par défaut en cas d'erreur
    lv_dropdown_set_selected(ui_LangDropdown, 0);
}

// Met à jour l'interface en fonction de la langue courante
void update_ui_language(void) {
    lv_label_set_text(ui_Labelphoto, translate(TEXT_NOM_PHOTOTYPE));
    lv_dropdown_set_text(ui_PhototypeLists, translate(TEXT_PHOTOTYPE));
    lv_label_set_text(ui_Label7, translate(TEXT_NOM_SOIN));
    lv_dropdown_set_text(ui_SoinsLists, translate(TEXT_SOIN));
    lv_label_set_text(ui_Labeltps, translate(TEXT_TOTAL_SOIN));
    lv_label_set_text(ui_Label10, translate(TEXT_RESTANT_SOIN));
    lv_label_set_text(ui_Label2, translate(TEXT_START));
    lv_label_set_text(ui_Label3, translate(TEXT_PAUSE));
    lv_label_set_text(ui_Label4, translate(TEXT_STOP));
    update_dropdown_languages();
    set_dropdown_language_selection();  // Assure que la langue affichée correspond à current_language
}

// Initialisation du dropdown langue (à appeler dans ton init UI)
    ui_LangDropdown = lv_dropdown_create(ui_MenuSoins);

    update_dropdown_languages();

    lv_obj_set_size(ui_LangDropdown, 155, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_LangDropdown, 315, -200);
    lv_obj_set_align(ui_LangDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LangDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    // Styles du dropdown
    lv_dropdown_set_symbol(ui_LangDropdown, NULL);
    lv_obj_set_style_pad_right(ui_LangDropdown, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(ui_LangDropdown, LV_OPA_TRANSP, LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(ui_LangDropdown, lv_color_hex(0x444444), LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LangDropdown, LV_OPA_COVER, LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_LangDropdown, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LangDropdown, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LangDropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_LangDropdown), &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Définit la sélection par défaut selon current_language
    set_dropdown_language_selection();

        // Fonction appelée quand on change la langue via le dropdown
    void event_lang_dropdown(lv_event_t * e) {
        uint32_t selected_index = lv_dropdown_get_selected(ui_LangDropdown);
        if (selected_index < LANG_DROPDOWN_COUNT) {
            current_language = language_ids[selected_index];
            change_language(current_language);
            update_ui_language();
        }
    }
    // Ajoute l'event handler pour la sélection
    lv_obj_add_event_cb(ui_LangDropdown, event_lang_dropdown, LV_EVENT_VALUE_CHANGED, NULL);


    // Phototypes Dropdown
    char options_photo[512] = "";
    for (int i = 0; i < NB_Photo; i++) {
        strcat(options_photo, phototypes[i].nom);
        strcat(options_photo, "\n");
    }
    ui_PhototypeLists = lv_dropdown_create(ui_MenuSoins);
    lv_dropdown_set_options(ui_PhototypeLists, options_photo);
    //lv_dropdown_set_text(ui_PhototypeLists, "Phototype");
    lv_dropdown_set_text(ui_PhototypeLists, translate(TEXT_PHOTOTYPE));
    lv_obj_set_size(ui_PhototypeLists, 260, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_PhototypeLists, -258, -200);
    lv_obj_set_align(ui_PhototypeLists, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PhototypeLists, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    // Styles dropdown principal
    lv_obj_set_style_text_color(ui_PhototypeLists, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PhototypeLists, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PhototypeLists, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_PhototypeLists), &ui_font_Roboto_24,LV_PART_MAIN | LV_STATE_DEFAULT);

    // Soins Dropdown
    char options_soins[256] = "";
    for (int i = 0; i < NB_SOIN; i++) {
        strcat(options_soins, translate(soins[i].id));
        if (i < NB_SOIN - 1) strcat(options_soins, "\n");
    }
    ui_SoinsLists = lv_dropdown_create(ui_MenuSoins);
    lv_dropdown_set_options(ui_SoinsLists, options_soins);
    lv_dropdown_set_text(ui_SoinsLists, translate(TEXT_SOIN));
    lv_obj_set_size(ui_SoinsLists, 260, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_SoinsLists, 48, -200);
    lv_obj_set_align(ui_SoinsLists, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SoinsLists, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    

    // Styles dropdown principal
    lv_obj_set_style_text_color(ui_SoinsLists, lv_color_hex(0x0B0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoinsLists, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SoinsLists, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SoinsLists), &ui_font_Roboto_24,LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoinsLists, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    //  Désactiver le dropdown soins au départ
    lv_obj_add_state(ui_SoinsLists, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_SoinsLists, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SoinsLists, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DISABLED);

    //  Ajouter les events pour le comportement logique
    lv_obj_add_event_cb(ui_PhototypeLists, eventPhototypes, LV_EVENT_VALUE_CHANGED, NULL); // Quand un phototype est choisi
    lv_obj_add_event_cb(ui_SoinsLists, eventSoins, LV_EVENT_VALUE_CHANGED, NULL);           // Quand un soin est choisi
    lv_obj_add_event_cb(ui_LangDropdown, event_lang_dropdown, LV_EVENT_VALUE_CHANGED, NULL); //Quand une langue est choisi



    // === Création du bouton PLAY ===
    ui_PlayButton = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_PlayButton, 130);
    lv_obj_set_height(ui_PlayButton, 90);
    lv_obj_set_x(ui_PlayButton, -291);
    lv_obj_set_y(ui_PlayButton, 184);
    lv_obj_set_align(ui_PlayButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlayButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xE61414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //desactivation initiale
    lv_obj_add_state(ui_PlayButton, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT); // Gris // Gris au début
    lv_obj_set_style_bg_opa(ui_PlayButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_PlayButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, translate(TEXT_START));
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);


    // === Création du bouton PAUSE ===
    ui_PauseButton = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_PauseButton, 130);
    lv_obj_set_height(ui_PauseButton, 90);
    lv_obj_set_x(ui_PauseButton, 2);
    lv_obj_set_y(ui_PauseButton, 184);
    lv_obj_set_align(ui_PauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PauseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // --- Désactivation initiale (gris) ---
    lv_obj_add_state(ui_PauseButton, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_PauseButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN);  // gris

    ui_Label3 = lv_label_create(ui_PauseButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, translate(TEXT_PAUSE));//pause
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // === Création du bouton STOP ===
    ui_StopButton = lv_btn_create(ui_MenuSoins);
    lv_obj_set_width(ui_StopButton, 130);
    lv_obj_set_height(ui_StopButton, 90);
    lv_obj_set_x(ui_StopButton, 298);
    lv_obj_set_y(ui_StopButton, 184);
    lv_obj_set_align(ui_StopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // --- Désactivation initiale (gris) ---
    lv_obj_add_state(ui_StopButton, LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_StopButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, translate(TEXT_STOP));//stop
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Panel1 = lv_obj_create(ui_MenuSoins);
    lv_obj_set_width(ui_Panel1, 782);
    lv_obj_set_height(ui_Panel1, 295);
    lv_obj_set_x(ui_Panel1, -1);
    lv_obj_set_y(ui_Panel1, -21);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    lv_obj_add_event_cb(ui_SoinsLists, ui_event_SoinsDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PhototypeLists, ui_event_PhototypeDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayButton, ui_event_PlayButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PauseButton, ui_event_PauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton, ui_event_StopButton, LV_EVENT_ALL, NULL);

    int y_start = -140;
    int x_start = -190;
    int spacing = 60; // espace vertical entre les éléments

    // Label: "Nom du Phototype :"
    ui_Labelphoto = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_Labelphoto, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Labelphoto, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Labelphoto, x_start);
    lv_obj_set_y(ui_Labelphoto, y_start);
    lv_obj_set_align(ui_Labelphoto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelphoto, translate(TEXT_NOM_PHOTOTYPE)); //phototypes
    lv_obj_set_style_text_font(ui_Labelphoto, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Label: "Nom du soin :"
    ui_Label7 = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label7, x_start);
    lv_obj_set_y(ui_Label7, y_start + spacing);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, translate(TEXT_NOM_SOIN));//soins
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Label: "Temps total soins :"
    ui_Labeltps = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_Labeltps, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Labeltps, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Labeltps, x_start);
    lv_obj_set_y(ui_Labeltps, y_start + 2 * spacing);
    lv_obj_set_align(ui_Labeltps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeltps, translate(TEXT_TOTAL_SOIN));
    lv_obj_set_style_text_font(ui_Labeltps, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Label: "Temps restant soins :"
    ui_Label10 = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label10, x_start);
    lv_obj_set_y(ui_Label10, y_start + 3 * spacing);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, translate(TEXT_RESTANT_SOIN));//tps restants soin
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Affichage dynamique dans l'écran de soins :

    int y_soins_start = -140;
    int soins_spacing = 60;

    // Nom du phototype
    ui_NomPhototype = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_NomPhototype, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_NomPhototype, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_NomPhototype, x_start+300);
    lv_obj_set_y(ui_NomPhototype, y_soins_start);
    lv_obj_set_align(ui_NomPhototype, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NomPhototype, "");
    lv_obj_set_style_text_color(ui_NomPhototype, lv_color_hex(0xFA0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NomPhototype, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NomPhototype, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Nom du soin
    ui_NomsoinLabel = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_NomsoinLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_NomsoinLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_NomsoinLabel, x_start+300);
    lv_obj_set_y(ui_NomsoinLabel, y_soins_start + soins_spacing);
    lv_obj_set_align(ui_NomsoinLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NomsoinLabel, "");
    lv_obj_set_style_text_color(ui_NomsoinLabel, lv_color_hex(0xFA0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NomsoinLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NomsoinLabel, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Temps total
    ui_TempstotalsoinsLabel = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_TempstotalsoinsLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TempstotalsoinsLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TempstotalsoinsLabel, x_start+300);
    lv_obj_set_y(ui_TempstotalsoinsLabel, y_soins_start + 2 * soins_spacing);
    lv_obj_set_align(ui_TempstotalsoinsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempstotalsoinsLabel, "");
    lv_obj_set_style_text_color(ui_TempstotalsoinsLabel, lv_color_hex(0xE90F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempstotalsoinsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempstotalsoinsLabel, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Temps restant
    ui_TempsrestantsoinsLabel = lv_label_create(ui_MenuSoins);
    lv_obj_set_width(ui_TempsrestantsoinsLabel, 164);
    lv_obj_set_height(ui_TempsrestantsoinsLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TempsrestantsoinsLabel, x_start+300);
    lv_obj_set_y(ui_TempsrestantsoinsLabel, y_soins_start + 3 * soins_spacing);
    lv_obj_set_align(ui_TempsrestantsoinsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempsrestantsoinsLabel, "");
    lv_obj_set_style_text_color(ui_TempsrestantsoinsLabel, lv_color_hex(0xF70B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempsrestantsoinsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempsrestantsoinsLabel, &ui_font_Roboto_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Créer la barre de progression
    ui_bar_progression = lv_bar_create(ui_Panel1);
    lv_obj_set_x(ui_bar_progression, 0);
    lv_obj_set_y(ui_bar_progression, 113);
    lv_obj_set_size(ui_bar_progression, 680, 15);
    lv_obj_align(ui_bar_progression, LV_ALIGN_BOTTOM_MID, 0, 10);
    lv_bar_set_value(ui_bar_progression, 0, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(ui_bar_progression, lv_color_hex(0xFFFFFF), LV_PART_MAIN);  // fond neutre
    

}