// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#include "ui.h"
#include "ui_helpers.h"
#include "ui_events.h"
#include "lang.h"


///////////////////// VARIABLES ////////////////////
void image_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_MenuSoins
void ui_MenuSoins_screen_init(void);
lv_obj_t * ui_MenuSoins;
void ui_event_PhototypeDropdown(lv_event_t * e);
void ui_event_SoinsDropdown(lv_event_t * e);
lv_obj_t * ui_PhototypeLists;
lv_obj_t * ui_SoinsLists;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Labeltps;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Labelphoto;
lv_obj_t * ui_NomsoinLabel;
lv_obj_t * ui_TempstotalsoinsLabel;
lv_obj_t * ui_TempsrestantsoinsLabel;
lv_obj_t * ui_NomPhototype;
void ui_event_PlayButton(lv_event_t * e);
lv_obj_t * ui_PlayButton;
lv_obj_t * ui_Label2;
void ui_event_PauseButton(lv_event_t * e);
lv_obj_t * ui_PauseButton;
lv_obj_t * ui_Label3;
void ui_event_StopButton(lv_event_t * e);
lv_obj_t * ui_StopButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_bar_progression;

 lv_obj_t * ui_LangDropdown;
 void event_lang_dropdown(lv_event_t * e);
 void update_dropdown_languages(void);
 void set_dropdown_language_selection(void);
// CUSTOM VARIABLES


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_event_ImgButton2(lv_event_t * e);
void ui_event_HomeScrenn(lv_event_t * e);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_ImgButton2;
// CUSTOM VARIABLES


// SCREEN: ui_BLEScreen
void ui_BLEScreen_screen_init(void);
lv_obj_t * ui_BLEScreen;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image3;
void ui_event_BLEScreen(lv_event_t * e);
lv_obj_t * ui_ExitButton;
// CUSTOM VARIABLES


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void image_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
///////////////////// FUNCTIONS ////////////////////void ui_init(void)
void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_MenuSoins_screen_init();
    ui_BLEScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}


void ui_event_HomeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SHORT_CLICKED) {
        // Changer d'écran vers le menu de soins avec animation de fondu
        _ui_screen_change(&ui_MenuSoins, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuSoins_screen_init);
    }
}

void ui_event_BLEScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        // Changer d'écran vers l'écran d'accueil avec animation de fondu
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        // Changer d'écran vers le menu des soins avec animation de fondu
        _ui_screen_change(&ui_MenuSoins, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MenuSoins_screen_init);
    }
}

//////////

void ui_event_SoinsDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        eventSoins(e);
    }
}

void ui_event_PhototypeDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        eventPhototypes(e);
    }
}

void ui_event_PlayButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PlayButtonevent(e);
    }
}

void ui_event_PauseButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PauseButtonevent(e);
    }
}

void ui_event_StopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StopButtonevent(e);
    }
}
///////////////////// SCREENS ////////////////////


void update_play_button_state()
{
    // Vérifie si les deux (phototype et soin) sont sélectionnés
    if (phototype_selectionne != NULL && soin_selectionne != NULL) {
        // Si les deux sont sélectionnés, on active le bouton et on le met en vert
        lv_obj_clear_state(ui_PlayButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0x00FF00), LV_PART_MAIN); // Vert
    } else {
        // Si l'un des deux n'est pas sélectionné, on désactive le bouton et on le met en gris
        lv_obj_add_state(ui_PlayButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_PlayButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT); // Gris
    }
}
bool play_button_active = false;
void update_pause_button_state()
{
    // Vérifie si les deux (phototype et soin) sont sélectionnés
    if (phototype_selectionne != NULL && soin_selectionne != NULL && play_button_active) {
         // Si les deux sont sélectionnés et Play est actif, on active le bouton Pause
        lv_obj_clear_state(ui_PauseButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_PauseButton, lv_color_hex(0xFFFF00), LV_PART_MAIN); // Jaune
    } else {
        // Si l'un des deux (phototype ou soin) n'est pas sélectionné ou Play n'est pas activé, on désactive le bouton Pause
        lv_obj_add_state(ui_PauseButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_PauseButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN); // Gris
    }
}
bool pause_button_active = false;
void update_stop_button_state()
{
    // Vérifie si les deux (phototype et soin) sont sélectionnés
    if (phototype_selectionne != NULL && soin_selectionne != NULL && pause_button_active) {
        
        lv_obj_clear_state(ui_StopButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0xFF0000), LV_PART_MAIN); // rouge
    } else {
        // Si l'un des deux n'est pas sélectionné, on désactive le bouton et on le met en gris
        lv_obj_add_state(ui_StopButton, LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(ui_StopButton, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT); // Gris
    }
}
