// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Boxlight_SLS_00

#ifndef _BOXLIGHT_SLS_00_UI_H
#define _BOXLIGHT_SLS_00_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_MenuSoins
void ui_MenuSoins_screen_init(void);
extern lv_obj_t * ui_MenuSoins;
extern lv_obj_t * ui_PhototypeLists;
extern lv_obj_t * ui_SoinsLists;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Roboto_16);
LV_FONT_DECLARE(ui_font_Roboto_24);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
